### ISSUE TITLE
fastentrypoints missing (causing install to fail)

### ISSUE THREAD

**Issue by ltalirz** [AntimoMarrazzo/aiida-z2pack#5]
`setup.py` imports `fastentrypoints` (which is not part of the repository)
https://github.com/AntimoMarrazzo/aiida-z2pack/blob/d8b8ff162c4cbbe93c5815840a0c809554bb603c/setup.py#L7

This used to be installed by aiida-core (more or less by mistake) in a package `utils` but it no longer is.

I'm not sure this is needed at all here (in which case the line can simply be deleted). 
If it is required, then I suggest you follow the approach of aiida-core and add a `pyproject.toml` that contains `fastentrypoints` as a build dependency

https://github.com/aiidateam/aiida-core/blob/develop/pyproject.toml

**Comment by Crivella** [comment]
Fixed by #6
